
all: choice confirm countln ncat uptime

choice:
	gcc -Wall -Werror -g choice.c functions.c -o choice

confirm:
	gcc -Wall -Werror -g confirm.c functions.c -o confirm

countln:
	gcc -Wall -Werror -g countln.c functions.c 7utils.h -o countln

ncat:
	gcc -Wall -Werror -g ncat.c 7utils.h -o ncat

uptime:
	gcc -Wall -Werror -g uptime.c -o uptime

